[custom]
; DNS检测
; https://browserleaks.com/dns
; https://ipleak.net/

; 定阅转换
; https://sub.flyway.eu.org  ; https://sub-api.flyway.eu.org

; 私人反代订阅 需要CF变量中设置其它第三方订阅地址 ; 或者不修改变量地址,直接在反代订阅地址后面加上：  &bd=https://v.id9.cc  (这会使用 https://v.id9.cc 翻盖CF反代变量中的第三方地址)
; https://p-sub.koala.workers.dev/

; 其它转换
; https://sub.dler.io/
; https://subcsub.com/
; https://nexconvert.com/
; https://api.nameless13.com/
; https://acl4ssr-sub.github.io/
; https://sub.tsutsu.one
; https://acl4ssr-sub.github.io
; https://sub.789.st
; https://sub.v1.mk
; https://apisub.vercel.app
; https://newsubfly.vercel.app

; https://www.youtube.com/watch?v=D841V_xgykg 视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！
;规则说明：https://github.com/tindy2013/subconverter/blob/master/README-cn.md

;更多规则：
; https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
; https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash

; 特殊文件格式链接前加 clash-classic: 如 ruleset=👨🏿‍💻 GitHub,clash-classic:https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml

;   远程配置
;   https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/flash.ini




;规则集定义（越少越好，小的集靠前，大的靠后）
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/Direct.list
ruleset=🚀 节点选择,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/Proxy.list
ruleset=🤖 AI-xjp,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/AI-xjp.list
ruleset=🤖 AI,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/AI.list
ruleset=🤖 AI,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=⛩️ 日区专用,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/JP.list
;谷歌FCM：消息推送
ruleset=📢 谷歌FCM,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list  
ruleset=📹 YouTube,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🍀 Google,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=💧 Copilot,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🐬 OneDrive,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🎥 Netflix,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎵 TikTok,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=👨🏿‍💻 GitHub,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list

ruleset=⛔ 阻止联网,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/block.list
ruleset=🎨 Adobe,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/ADOBE.list
ruleset=🕹️ nintendo,https://ghfast.top/raw.githubusercontent.com/fllywaay/flash-rules/refs/heads/master/nintendo.list


ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎞️ 国内媒体,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎮 游戏平台,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
; ruleset=🎮 游戏平台,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🌍 国外媒体,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=⏬ 下载专用,https://ghfast.top/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
; ruleset=🚀 节点选择,[]GEOSITE,TW
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOIP,TW,no-resolve
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
; ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL


;策略组定义（名称与上面名称必须对应）符号^为筛选去除
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]❇️ 优质节点`[]🐸 手动切换`[]🎏 JUST`[]🎏 GlaDOS`[]🎏 Xsus`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🌐 其他节点`[]🛩️ 高速节点`[]🕊️ 便宜节点`[]DIRECT`[]REJECT
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🐸 手动切换`[]🎏 JUST`[]🎏 GlaDOS`[]🎏 Xsus
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=❇️ 优质节点`url-test`(JMS|GLaDOS|dd-bd)`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🎏 JUST`url-test`JMS`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🎏 GlaDOS`url-test`GLaDOS`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🎏 Xsus`url-test`\s+([\u4e00-\u9fff]+)\s+(\d+)`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🤖 AI-xjp`select`[]🔯 加坡故转`[]🇸🇬 加坡节点`[]🚀 节点选择`[]🔯 日本故转`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🐸 手动切换`[]🎏 JUST`[]🎏 GlaDOS`[]🎏 Xsus
custom_proxy_group=🤖 AI`select`[]🔯 美国故转`[]🚀 节点选择`[]🔯 日本故转`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🐸 手动切换`[]🎏 JUST`[]🎏 GlaDOS`[]🎏 Xsus
custom_proxy_group=⛩️ 日区专用`select`[]🔯 日本故转`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🎨 Adobe`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🕹️ nintendo`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=⛔ 阻止联网`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=💧 Copilot`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 加坡节点`[]🐸 手动切换
custom_proxy_group=🐬 OneDrive`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 日本故转`[]🔯 香港故转`[]🔯 加坡故转`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🪟 Microsoft`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 日本故转`[]🔯 香港故转`[]🔯 加坡故转`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🔯 美国故转`[]🎏 JUST`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]🚀 节点选择`[]🔯 美国故转`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🇹🇼 台湾节点`[]🐸 手动切换
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇲 美国节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=🎵 TikTok`select`[]🔯 美国故转`[]🇺🇲 美国节点`[]🚀 节点选择`[]🔯 日本故转`[]🔯 加坡故转`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🎥 Netflix`select`[]🎥 奈飞节点`[]🚀 节点选择`[]🔯 美国故转`[]🇺🇲 美国节点`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🔯 美国故转`[]🇺🇲 美国节点`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🐸 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🔯 美国故转`[]🇺🇲 美国节点`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🐸 手动切换
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=⏬ 下载专用`select`[]DIRECT`[]🕊️ 便宜节点`[]🚀 节点选择`[]🔯 美国故转`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
; custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择
; custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`[]🚀 节点选择
; custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT`[]🚀 节点选择
; custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚂 下载节点`select`(-D1-|下载)
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🛩️ 高速节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States))^((?!(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$
custom_proxy_group=🕊️ 便宜节点`url-test`.*(0.5|0.5倍|0.5x|free|flyway).*`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深港|US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇹🇼 台湾节点`select`(?=.*(台湾|TW|Taiwan|🇹🇼|中国|CN))^((?!(深港|US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇸🇬 加坡节点`select`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇺🇲 美国节点`url-test`(美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States)*$`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🔯 美国故转`fallback`!!GROUPID=!0!!(美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States)(?!.*(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🔯 香港故转`fallback`!!GROUPID=!0!!(香港|HK|Hong Kong|🇭🇰|HongKong)(?!.*(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🔯 日本故转`fallback`!!GROUPID=!0!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)(?!.*(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🔯 加坡故转`fallback`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🍃 香港均衡`load-balance`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🌐 其他节点`select`(^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore|美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States|台湾|TW|Taiwan|🇹🇼)).*)


;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true

